### ISSUE TITLE
CodeMap & Outline plugin compatibility 

### ISSUE THREAD

**Issue by ldm1417** [oleg-shilo/sublime-codemap#38]
Hello,
Are the CodeMap and the Outline Plug-Ins compatible one with another? It seems they are not .... 
When I click inside of the Outline Plug-In, the cursor jumps to the CodeMap Panel, not to the File Tab.
Is this the Outline's or CodeMap's problem? Could be fixed? 
Thanks!

**Comment by oleg-shilo** [comment]
They are completely independent plugins. Even though both plugins are aiming for somewhat similar UX.

Though CodeMap is different in terms of being extendable through custom mappers so it can support whatever content type you want as long as you define the mapping algorithm. 

BTW the same plugin is available for VSCode though its collection of ready to go mappers is much larger. 14 vs 4 for Sublime version.

Anyway. Since the undesired behaviour is triggered by clicking on Outline Plugin area I would start digging there.

CodeMap plugin indeed triggers focus change but only if you click on the CodeMap tab content.

**Comment by ldm1417** [comment]
Yes, please dig it in ... It seems the Outline and CodeMap Plug-Ins don't work together... Once clicking on the Outline Pane, the cursor jumps to the CodeMap Pan (instead of to the Editor/Main Pane).
As for the VSCode's "ready-to-go" language mappers, could they be easily converted to the Sublime's code mappers? 
Could I ask you to prepare a CodeMapper for the SystemVerilog language?

**Comment by oleg-shilo** [comment]
Sorry, I think I have created some confusion with my response.

I meant that since it is Outline Pluging who is triggering the behaviour, which you are trying to stop, you need to debug this plugin or ask the plugin owner for assistance.

I have no knowledge of this plugin or bandwidth for that. 
I am currently completely flooded with support for my other OpenSource products that require my attention.

As for developing a new mapper, the plugin architecture is designed the way so the users themselves can define new mappers if required. Thus the majority of the VSCode mappers is developed and then contributed by the users.

It means that if you develop the plugin for SystemVerilog and share it I can include it in the plugin package so others can benefit from it too.

Writing a mapper is rather simple. This is the example of the MarkdownIt mapper: https://github.com/oleg-shilo/sublime-codemap/blob/master/custom_mappers/md.py

You can even go with so-called universal mapper that only requires a regular expression definition in the config file: https://github.com/oleg-shilo/sublime-codemap#universal-mapper

>As for the VSCode's "ready-to-go" language mappers, could they be easily converted to the Sublime's code mappers?
Yes but not easily. though not very hard either :)

VSCode is using TypeScrypt as an extension/plugin language for complete custom mappers. But the regular expressions based mappers can be definitely easily borrowed from VSCode and injected into ST configuration. Though SystemVerilog mapper does not exist on VSCode neither.
